---

- name: Remover versões legadas do docker
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io

- name: Adicionar chave gpg para o apt
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: Adicionar repositório apt do docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true

- name: Instalar containerd 1.5.10-1
  apt:
    name: containerd.io=1.5.10-1
    state: present
    update_cache: yes
    force: true

- name: Ensure containerd config directory exists.
  file:
    path: /etc/containerd
    state: directory
  register: containerd_dir

- name: Get defaults from containerd.
  command: containerd config default
  changed_when: false
  register: containerd_config_default
  when: containerd_config_default_write

- name: Prepare containerd/config.toml from default config
  copy:
    dest: /tmp/containerd_config.toml
    content: "{{ containerd_config_default.stdout }}"
  when: containerd_config_default_write
  changed_when: false
- name: Set Cgroup driver to systemd
  lineinfile:
    insertafter: '.*\[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options\]$'
    line: '          SystemdCgroup = true'
    state: present
    path: /tmp/containerd_config.toml
  when: containerd_config_default_write and containerd_config_cgroup_driver_systemd
  changed_when: false

- name: Make sure  SystemdCgroup = false is not set
  ansible.builtin.lineinfile:
    path: /tmp/containerd_config.toml
    state: absent
    line: '            SystemdCgroup = false'
  when: containerd_config_default_write and containerd_config_cgroup_driver_systemd
  changed_when: false

- name: Copy config.toml to /etc/containerd
  copy:
    remote_src: true
    src: /tmp/containerd_config.toml
    dest: /etc/containerd/config.toml
  when: containerd_config_default_write

- name: Cleanup temporary file
  file:
    path: /tmp/containerd_config.toml
    state: absent
  changed_when: false
  
- name: restart containerd
  service:
    name: containerd
    state: restarted

- name: Instalar docker-ce 5:20.10.17
  apt:
    name:
      - "docker-ce=5:20.10.17~3-0~{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}"
      - "docker-ce-cli=5:20.10.17~3-0~{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}"
    state: present
    force: True

- name: Configurar hold dos pacotes
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Instalar pip
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
    force: true
  with_items:
    - python3-pip

- name: Instalar python-docker 
  pip:
    name: docker
    state: present

- name: Copiar template do daemon.json
  template:
    src: templates/daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Restartar serviço do docker
  service:
    name: docker
    enabled: yes
    state: restarted
    daemon_reload: yes